In [4]:
import os
import pandas as pd


In [3]:
pd.__version__

'2.2.2'

In [6]:
dt = pd.read_csv(os.path.join("..", "datasets", "ceny_produktow_renamed.csv"), sep=";")

In [7]:
dt

province  \
0              PODKARPACKIE   
1                   ŁÓDZKIE   
2        KUJAWSKO-POMORSKIE   
3              DOLNOŚLĄSKIE   
4       WARMIŃSKO-MAZURSKIE   
...                     ...   
149935   KUJAWSKO-POMORSKIE   
149936              ŁÓDZKIE   
149937          MAŁOPOLSKIE   
149938  WARMIŃSKO-MAZURSKIE   
149939          MAZOWIECKIE   

                                            product_types currency  \
0                                                     NaN       zł   
1                                                     NaN       zł   
2                                                     NaN       zł   
3                                                     NaN       zł   
4                                                     NaN       zł   
...                                                   ...      ...   
149935                                                NaN       zł   
149936  cukier biały z buraków cukrowych, workowany - ...       zł   
149937                                                NaN       zł   
149938                                                NaN       zł   
149939                                                NaN       zł   

        product_group_id                                    product_line  \
0                      2              szynka wieprzowa gotowana - za 1kg   
1                      4                                  chleb - za 1kg   
2                      2              kiszka kaszana jęczmienna - za 1kg   
3                      2                    kurczęta patroszone - za 1kg   
4                      2                        salceson Włoski - za 1kg   
...                  ...                                             ...   
149935                 2       mięso  wieprzowe (boczek surowy) - za 1kg   
149936                 3                                             NaN   
149937                 4  chleb mieszany zwykły (pszenno-żytni) - za 1kg   
149938                 2       mięso wołowe bez kości (z udźca) - za 1kg   
149939                 4              kasza jęczmienna Mazurska - za 1kg   

        value     date  
0       21.37   2013-3  
1         NaN   2018-2  
2        3.55  2019-12  
3        6.14   2019-2  
4        5.63   2002-3  
...       ...      ...  
149935  12.15  2016-11  
149936   0.00   2012-5  
149937   3.05   2008-6  
149938  11.87  2000-11  
149939   0.16  2005-10  

[149940 rows x 7 columns]

In [8]:
dt.head()

province product_types currency  product_group_id  \
0         PODKARPACKIE           NaN       zł                 2   
1              ŁÓDZKIE           NaN       zł                 4   
2   KUJAWSKO-POMORSKIE           NaN       zł                 2   
3         DOLNOŚLĄSKIE           NaN       zł                 2   
4  WARMIŃSKO-MAZURSKIE           NaN       zł                 2   

                         product_line  value     date  
0  szynka wieprzowa gotowana - za 1kg  21.37   2013-3  
1                      chleb - za 1kg    NaN   2018-2  
2  kiszka kaszana jęczmienna - za 1kg   3.55  2019-12  
3        kurczęta patroszone - za 1kg   6.14   2019-2  
4            salceson Włoski - za 1kg   5.63   2002-3

In [9]:
dt.tail()

province  \
149935   KUJAWSKO-POMORSKIE   
149936              ŁÓDZKIE   
149937          MAŁOPOLSKIE   
149938  WARMIŃSKO-MAZURSKIE   
149939          MAZOWIECKIE   

                                            product_types currency  \
149935                                                NaN       zł   
149936  cukier biały z buraków cukrowych, workowany - ...       zł   
149937                                                NaN       zł   
149938                                                NaN       zł   
149939                                                NaN       zł   

        product_group_id                                    product_line  \
149935                 2       mięso  wieprzowe (boczek surowy) - za 1kg   
149936                 3                                             NaN   
149937                 4  chleb mieszany zwykły (pszenno-żytni) - za 1kg   
149938                 2       mięso wołowe bez kości (z udźca) - za 1kg   
149939                 4              kasza jęczmienna Mazurska - za 1kg   

        value     date  
149935  12.15  2016-11  
149936   0.00   2012-5  
149937   3.05   2008-6  
149938  11.87  2000-11  
149939   0.16  2005-10

In [10]:
dt.sample(10)

province product_types currency  product_group_id  \
73993                POLSKA           NaN       zł                 2   
41213                POLSKA           NaN       zł                 2   
38213   WARMIŃSKO-MAZURSKIE           NaN       zł                 4   
33047              OPOLSKIE           NaN       zł                 2   
148898             LUBUSKIE           NaN       zł                 2   
108997         DOLNOŚLĄSKIE           NaN       zł                 4   
93925    ZACHODNIOPOMORSKIE           NaN       zł                 2   
24536          PODKARPACKIE           NaN       zł                 4   
49470          DOLNOŚLĄSKIE           NaN       zł                 2   
29914             PODLASKIE           NaN       zł                 4   

                                            product_line  value     date  
73993   konserwa mięsna wieprzowa Turystyczna - za 300 g   2.34  2015-12  
41213          mięso  wieprzowe (boczek surowy) - za 1kg   9.26   2001-7  
38213               kasza gryczana prażona cała - za 1kg   0.00   2001-1  
33047                           salceson Włoski - za 1kg  10.63   2012-8  
148898             pstrąg świeży niepatroszony - za 1 kg   0.00  2016-11  
108997    chleb mieszany zwykły (pszenno-żytni) - za 1kg   5.50   2015-7  
93925              pstrąg świeży niepatroszony - za 1 kg  12.70   2011-4  
24536               kasza gryczana prażona cała - za 1kg   0.00   2001-1  
49470               śledź solony, niepatroszony - za 1kg   0.00  2017-12  
29914         mąka pszenna Poznańska, workowana - za 1kg   0.00   2012-1

In [11]:
dt.shape

(149940, 7)

In [12]:
dt.describe()

product_group_id          value
count     149940.000000  137088.000000
mean           2.571429       6.615227
std            1.022206      34.112858
min            1.000000       0.000000
25%            2.000000       0.000000
50%            2.000000       3.090000
75%            4.000000      10.920000
max            4.000000    3000.000000

In [14]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149940 entries, 0 to 149939
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   province          149940 non-null  object 
 1   product_types     34272 non-null   object 
 2   currency          149940 non-null  object 
 3   product_group_id  149940 non-null  int64  
 4   product_line      115668 non-null  object 
 5   value             137088 non-null  float64
 6   date              149940 non-null  object 
dtypes: float64(1), int64(1), object(5)
memory usage: 8.0+ MB


In [15]:
dt.columns

Index(['province', 'product_types', 'currency', 'product_group_id',
       'product_line', 'value', 'date'],
      dtype='object')

In [20]:
'ala ma kota'[0:3]
# [start:stop:step]

'ala'

In [19]:
# dt.loc[start:stop:step, start:stop:step] -> [rows, columns]
dt.loc[:, :]

province  \
0              PODKARPACKIE   
1                   ŁÓDZKIE   
2        KUJAWSKO-POMORSKIE   
3              DOLNOŚLĄSKIE   
4       WARMIŃSKO-MAZURSKIE   
...                     ...   
149935   KUJAWSKO-POMORSKIE   
149936              ŁÓDZKIE   
149937          MAŁOPOLSKIE   
149938  WARMIŃSKO-MAZURSKIE   
149939          MAZOWIECKIE   

                                            product_types currency  \
0                                                     NaN       zł   
1                                                     NaN       zł   
2                                                     NaN       zł   
3                                                     NaN       zł   
4                                                     NaN       zł   
...                                                   ...      ...   
149935                                                NaN       zł   
149936  cukier biały z buraków cukrowych, workowany - ...       zł   
149937                                                NaN       zł   
149938                                                NaN       zł   
149939                                                NaN       zł   

        product_group_id                                    product_line  \
0                      2              szynka wieprzowa gotowana - za 1kg   
1                      4                                  chleb - za 1kg   
2                      2              kiszka kaszana jęczmienna - za 1kg   
3                      2                    kurczęta patroszone - za 1kg   
4                      2                        salceson Włoski - za 1kg   
...                  ...                                             ...   
149935                 2       mięso  wieprzowe (boczek surowy) - za 1kg   
149936                 3                                             NaN   
149937                 4  chleb mieszany zwykły (pszenno-żytni) - za 1kg   
149938                 2       mięso wołowe bez kości (z udźca) - za 1kg   
149939                 4              kasza jęczmienna Mazurska - za 1kg   

        value     date  
0       21.37   2013-3  
1         NaN   2018-2  
2        3.55  2019-12  
3        6.14   2019-2  
4        5.63   2002-3  
...       ...      ...  
149935  12.15  2016-11  
149936   0.00   2012-5  
149937   3.05   2008-6  
149938  11.87  2000-11  
149939   0.16  2005-10  

[149940 rows x 7 columns]

In [21]:
# 5 pierwszych wierszy i wszystkie columns
dt.loc[:5, :]

province                           product_types currency  \
0         PODKARPACKIE                                     NaN       zł   
1              ŁÓDZKIE                                     NaN       zł   
2   KUJAWSKO-POMORSKIE                                     NaN       zł   
3         DOLNOŚLĄSKIE                                     NaN       zł   
4  WARMIŃSKO-MAZURSKIE                                     NaN       zł   
5       ŚWIĘTOKRZYSKIE  ogórki konserwowe całe 0,9l - za 1szt.       zł   

   product_group_id                        product_line  value     date  
0                 2  szynka wieprzowa gotowana - za 1kg  21.37   2013-3  
1                 4                      chleb - za 1kg    NaN   2018-2  
2                 2  kiszka kaszana jęczmienna - za 1kg   3.55  2019-12  
3                 2        kurczęta patroszone - za 1kg   6.14   2019-2  
4                 2            salceson Włoski - za 1kg   5.63   2002-3  
5                 1                                 NaN   0.28   2010-4

In [26]:
# dt.loc[:5, 'province':'currency']
dt.iloc[:5, :2]

province product_types
0         PODKARPACKIE           NaN
1              ŁÓDZKIE           NaN
2   KUJAWSKO-POMORSKIE           NaN
3         DOLNOŚLĄSKIE           NaN
4  WARMIŃSKO-MAZURSKIE           NaN

In [27]:
# cols province, currency, value, 5 rows
dt.loc[:5, ["province", "currency", "value"]]

province currency  value
0         PODKARPACKIE       zł  21.37
1              ŁÓDZKIE       zł    NaN
2   KUJAWSKO-POMORSKIE       zł   3.55
3         DOLNOŚLĄSKIE       zł   6.14
4  WARMIŃSKO-MAZURSKIE       zł   5.63
5       ŚWIĘTOKRZYSKIE       zł   0.28

In [28]:
dt.iloc[:5, [0, 2, 5]]

province currency  value
0         PODKARPACKIE       zł  21.37
1              ŁÓDZKIE       zł    NaN
2   KUJAWSKO-POMORSKIE       zł   3.55
3         DOLNOŚLĄSKIE       zł   6.14
4  WARMIŃSKO-MAZURSKIE       zł   5.63

In [29]:
dt.iloc[[1, 10, 20, 30, 40], [0, 2, 5]]

province currency  value
1               ŁÓDZKIE       zł    NaN
10  WARMIŃSKO-MAZURSKIE       zł   0.95
20              ŚLĄSKIE       zł   0.00
30        WIELKOPOLSKIE       zł  18.20
40              ŚLĄSKIE       zł  10.59

In [30]:
import numpy as np

In [31]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
x = [1, 2, 3] * 3
print(x)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [33]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [34]:
arr ** 6

array([     0,      1,     64,    729,   4096,  15625,  46656, 117649,
       262144, 531441])

In [35]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [36]:
arr[arr > 5]

array([6, 7, 8, 9])

In [38]:
type(dt)

pandas.core.frame.DataFrame

In [41]:
dt.loc[dt["date"] == '1888-0']

province product_types currency  product_group_id  \
11908              LUBUSKIE           NaN       zł                 2   
14765               ŚLĄSKIE           NaN       zł                 2   
16125   WARMIŃSKO-MAZURSKIE           NaN       zł                 2   
18737          DOLNOŚLĄSKIE           NaN       zł                 2   
20293        ŚWIĘTOKRZYSKIE           NaN       zł                 2   
33038              OPOLSKIE           NaN       zł                 2   
50542           MAŁOPOLSKIE           NaN       zł                 2   
51536         WIELKOPOLSKIE           NaN       zł                 2   
85091             PODLASKIE           NaN       zł                 2   
95997             POMORSKIE           NaN       zł                 2   
100513         PODKARPACKIE           NaN       zł                 2   
110578               POLSKA           NaN       zł                 2   
111306   KUJAWSKO-POMORSKIE           NaN       zł                 2   
123125            LUBELSKIE           NaN       zł                 2   
137245          MAZOWIECKIE           NaN       zł                 2   
144334   ZACHODNIOPOMORSKIE           NaN       zł                 2   
147385              ŁÓDZKIE           NaN       zł                 2   

                              product_line  value    date  
11908   karp świeży niepatroszony - za 1kg   8.17  1888-0  
14765   karp świeży niepatroszony - za 1kg   0.00  1888-0  
16125   karp świeży niepatroszony - za 1kg   8.03  1888-0  
18737   karp świeży niepatroszony - za 1kg   0.00  1888-0  
20293   karp świeży niepatroszony - za 1kg   7.94  1888-0  
33038   karp świeży niepatroszony - za 1kg   0.00  1888-0  
50542   karp świeży niepatroszony - za 1kg   0.00  1888-0  
51536   karp świeży niepatroszony - za 1kg   7.77  1888-0  
85091   karp świeży niepatroszony - za 1kg   0.00  1888-0  
95997   karp świeży niepatroszony - za 1kg   8.13  1888-0  
100513  karp świeży niepatroszony - za 1kg   0.00  1888-0  
110578  karp świeży niepatroszony - za 1kg   7.65  1888-0  
111306  karp świeży niepatroszony - za 1kg   6.87  1888-0  
123125  karp świeży niepatroszony - za 1kg   6.84  1888-0  
137245  karp świeży niepatroszony - za 1kg   0.00  1888-0  
144334  karp świeży niepatroszony - za 1kg   7.48  1888-0  
147385  karp świeży niepatroszony - za 1kg   0.00  1888-0

In [42]:
dt.query("date == '1888-0'")

province product_types currency  product_group_id  \
11908              LUBUSKIE           NaN       zł                 2   
14765               ŚLĄSKIE           NaN       zł                 2   
16125   WARMIŃSKO-MAZURSKIE           NaN       zł                 2   
18737          DOLNOŚLĄSKIE           NaN       zł                 2   
20293        ŚWIĘTOKRZYSKIE           NaN       zł                 2   
33038              OPOLSKIE           NaN       zł                 2   
50542           MAŁOPOLSKIE           NaN       zł                 2   
51536         WIELKOPOLSKIE           NaN       zł                 2   
85091             PODLASKIE           NaN       zł                 2   
95997             POMORSKIE           NaN       zł                 2   
100513         PODKARPACKIE           NaN       zł                 2   
110578               POLSKA           NaN       zł                 2   
111306   KUJAWSKO-POMORSKIE           NaN       zł                 2   
123125            LUBELSKIE           NaN       zł                 2   
137245          MAZOWIECKIE           NaN       zł                 2   
144334   ZACHODNIOPOMORSKIE           NaN       zł                 2   
147385              ŁÓDZKIE           NaN       zł                 2   

                              product_line  value    date  
11908   karp świeży niepatroszony - za 1kg   8.17  1888-0  
14765   karp świeży niepatroszony - za 1kg   0.00  1888-0  
16125   karp świeży niepatroszony - za 1kg   8.03  1888-0  
18737   karp świeży niepatroszony - za 1kg   0.00  1888-0  
20293   karp świeży niepatroszony - za 1kg   7.94  1888-0  
33038   karp świeży niepatroszony - za 1kg   0.00  1888-0  
50542   karp świeży niepatroszony - za 1kg   0.00  1888-0  
51536   karp świeży niepatroszony - za 1kg   7.77  1888-0  
85091   karp świeży niepatroszony - za 1kg   0.00  1888-0  
95997   karp świeży niepatroszony - za 1kg   8.13  1888-0  
100513  karp świeży niepatroszony - za 1kg   0.00  1888-0  
110578  karp świeży niepatroszony - za 1kg   7.65  1888-0  
111306  karp świeży niepatroszony - za 1kg   6.87  1888-0  
123125  karp świeży niepatroszony - za 1kg   6.84  1888-0  
137245  karp świeży niepatroszony - za 1kg   0.00  1888-0  
144334  karp świeży niepatroszony - za 1kg   7.48  1888-0  
147385  karp świeży niepatroszony - za 1kg   0.00  1888-0

In [43]:
dt.query('date > "2024-0"')

province product_types currency  product_group_id  \
1583         ŚWIĘTOKRZYSKIE           NaN       zł                 2   
35525             PODLASKIE           NaN       zł                 2   
43258               ŚLĄSKIE           NaN       zł                 2   
52595              LUBUSKIE           NaN       zł                 2   
56032         WIELKOPOLSKIE           NaN       zł                 2   
72048              OPOLSKIE           NaN       zł                 2   
73532               ŁÓDZKIE           NaN       zł                 2   
84515             LUBELSKIE           NaN       zł                 2   
86619             POMORSKIE           NaN       zł                 2   
98839    ZACHODNIOPOMORSKIE           NaN       zł                 2   
102878          MAZOWIECKIE           NaN       zł                 2   
109773   KUJAWSKO-POMORSKIE           NaN       zł                 2   
127052          MAŁOPOLSKIE           NaN       zł                 2   
129910               POLSKA           NaN       zł                 2   
135566  WARMIŃSKO-MAZURSKIE           NaN       zł                 2   
135910         DOLNOŚLĄSKIE           NaN       zł                 2   
148646         PODKARPACKIE           NaN       zł                 2   

                                product_line  value     date  
1583    filety z morszczuka mrożone - za 1kg   0.00  2099-13  
35525   filety z morszczuka mrożone - za 1kg   0.00  2099-13  
43258   filety z morszczuka mrożone - za 1kg  20.96  2099-13  
52595   filety z morszczuka mrożone - za 1kg   0.00  2099-13  
56032   filety z morszczuka mrożone - za 1kg  18.92  2099-13  
72048   filety z morszczuka mrożone - za 1kg   0.00  2099-13  
73532   filety z morszczuka mrożone - za 1kg   0.00  2099-13  
84515   filety z morszczuka mrożone - za 1kg  16.15  2099-13  
86619   filety z morszczuka mrożone - za 1kg  16.22  2099-13  
98839   filety z morszczuka mrożone - za 1kg   0.00  2099-13  
102878  filety z morszczuka mrożone - za 1kg   0.00  2099-13  
109773  filety z morszczuka mrożone - za 1kg  16.70  2099-13  
127052  filety z morszczuka mrożone - za 1kg   0.00  2099-13  
129910  filety z morszczuka mrożone - za 1kg  16.76  2099-13  
135566  filety z morszczuka mrożone - za 1kg  19.23  2099-13  
135910  filety z morszczuka mrożone - za 1kg   0.00  2099-13  
148646  filety z morszczuka mrożone - za 1kg   0.00  2099-13

In [44]:
dt.describe()

product_group_id          value
count     149940.000000  137088.000000
mean           2.571429       6.615227
std            1.022206      34.112858
min            1.000000       0.000000
25%            2.000000       0.000000
50%            2.000000       3.090000
75%            4.000000      10.920000
max            4.000000    3000.000000

In [45]:
dt.query("value == 3000")

province                       product_types currency  \
13724             POMORSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
18768          DOLNOŚLĄSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
22321    ZACHODNIOPOMORSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
31268          PODKARPACKIE  koncentrat pomidorowy 30% - za 1kg       zł   
36958           MAŁOPOLSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
62346         WIELKOPOLSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
70851           MAZOWIECKIE  koncentrat pomidorowy 30% - za 1kg       zł   
79924    KUJAWSKO-POMORSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
91306               ŁÓDZKIE  koncentrat pomidorowy 30% - za 1kg       zł   
96597              OPOLSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
104235               POLSKA  koncentrat pomidorowy 30% - za 1kg       zł   
122007             LUBUSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
130871       ŚWIĘTOKRZYSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
135863  WARMIŃSKO-MAZURSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
143420            PODLASKIE  koncentrat pomidorowy 30% - za 1kg       zł   
143997              ŚLĄSKIE  koncentrat pomidorowy 30% - za 1kg       zł   
146383            LUBELSKIE  koncentrat pomidorowy 30% - za 1kg       zł   

        product_group_id product_line   value    date  
13724                  1          NaN  3000.0  2003-1  
18768                  1          NaN  3000.0  2003-1  
22321                  1          NaN  3000.0  2003-1  
31268                  1          NaN  3000.0  2003-1  
36958                  1          NaN  3000.0  2003-1  
62346                  1          NaN  3000.0  2003-1  
70851                  1          NaN  3000.0  2003-1  
79924                  1          NaN  3000.0  2003-1  
91306                  1          NaN  3000.0  2003-1  
96597                  1          NaN  3000.0  2003-1  
104235                 1          NaN  3000.0  2003-1  
122007                 1          NaN  3000.0  2003-1  
130871                 1          NaN  3000.0  2003-1  
135863                 1          NaN  3000.0  2003-1  
143420                 1          NaN  3000.0  2003-1  
143997                 1          NaN  3000.0  2003-1  
146383                 1          NaN  3000.0  2003-1

In [49]:
pd.to_datetime(dt['date'], format='%Y-m')

ValueError: unconverted data remains when parsing with format "%Y": "-3", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [51]:
dt['product_types'].unique()


array([nan, 'ogórki konserwowe całe 0,9l - za 1szt.',
       'jaja kóże śfierze - za 666szt.',
       'koncentrat pomidorowy 30% - za 1kg',
       'mieszanka mrożona marchew i groszek - za 1kg',
       'cukier biały z buraków cukrowych, workowany - za 1kg',
       'sok jabłkowy, w opakowaniu kartonowym - za 1l',
       'sól warzona biała workowana - za 1kg',
       'czekolada naturalna pełna bez dodatków - za 1kg'], dtype=object)

In [53]:
dt.loc[dt['product_types'] == 'jaja kóże śfierze - za 666szt.'].shape


(4284, 7)

In [56]:
dt['province'].unique()

array(['PODKARPACKIE', 'ŁÓDZKIE', 'KUJAWSKO-POMORSKIE', 'DOLNOŚLĄSKIE',
       'WARMIŃSKO-MAZURSKIE', 'ŚWIĘTOKRZYSKIE', 'ZACHODNIOPOMORSKIE',
       'POLSKA', 'PODLASKIE', 'WIELKOPOLSKIE', 'POMORSKIE', 'MAŁOPOLSKIE',
       'ŚLĄSKIE', 'MAZOWIECKIE', 'LUBELSKIE', 'LUBUSKIE', 'OPOLSKIE'],
      dtype=object)

In [65]:
dt.loc[(dt['product_types'] == 'mieszanka mrożona marchew i groszek - za 1kg') & (dt['province'] == 'POLSKA') & (dt['date'].str.startswith('2015'))]

province                                 product_types currency  \
8542     POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
60491    POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
64981    POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
73561    POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
113640   POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
120465   POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
125079   POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
129550   POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
132374   POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
139865   POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
139966   POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   
142825   POLSKA  mieszanka mrożona marchew i groszek - za 1kg      EUR   

        product_group_id product_line     value     date  
8542                   1          NaN  0.824096   2015-1  
60491                  1          NaN  0.843373  2015-12  
64981                  1          NaN  0.816867  2015-11  
73561                  1          NaN  0.792771   2015-4  
113640                 1          NaN  0.884337  2015-10  
120465                 1          NaN  0.766265   2015-6  
125079                 1          NaN  0.840964   2015-8  
129550                 1          NaN  0.843373   2015-7  
132374                 1          NaN  0.860241   2015-3  
139865                 1          NaN  0.874699   2015-5  
139966                 1          NaN  0.804819   2015-2  
142825                 1          NaN  0.797590   2015-9

In [ ]:
np.logical_and()

In [70]:
data = dt.loc[np.logical_and(
    np.logical_and(
        dt['product_types'] == 'mieszanka mrożona marchew i groszek - za 1kg',
        dt['province'] == 'POLSKA'
    ),
    dt['date'].str.startswith('2015')
)]

data['value'].mean()

0.8291164658634539

In [77]:
'2015' < '2016-10' < '2017'

True

In [75]:
'2016-01'[:4] in ['2015', '2014']

False

In [82]:
years = ['2016', '2017', '2018']

data = dt.loc[np.logical_and(
    np.logical_and(
        dt['product_types'] == 'sok jabłkowy, w opakowaniu kartonowym - za 1l',
        dt['province'] == 'MAZOWIECKIE'
    ),
    dt['date'].str[:4].isin(years)
)]

data['value'].mean()

2.9172222222222226

In [92]:
years = [str(year) for year in range(2003, 2016)]

data = dt.loc[np.logical_and(
    np.logical_and(
        dt['product_types'] == 'koncentrat pomidorowy 30% - za 1kg',
        dt['province'] == 'DOLNOŚLĄSKIE'
    ),
    np.logical_and(
        dt['date'].str[:4].isin(years),
        dt['value'] > 0
    )
)]

data.loc[data['value'] != 3000].value.mean()
# data['value'].mean()

2.899090909090909